- name: Set IP Loopback
  hosts: SW_1
  gather_facts: no

  tasks:
    - name: Set loopback IPv4
      ios_l3_interface:
          name: loopback {{ item.name}}
          ipv4: 10.0.{{item.ip}}.1/24
      with_items:
          - {name: 0, ip: 1}
          - {name: 1, ip: 2}
          - {name: 2, ip: 3}
    - name: xem ip cac cong
      ios_command:
          commands:
              - sh ip int bri
      register: show_ip
    - debug: var=show_ip.stdout_lines  
      
